config/routes.rb
Rails.application.routes.draw do

	root 'static_pages#home'

	ActiveAdmin.routes(self)

	devise_for :users, controllers: {omniauth_callbacks: "omniauth_sessions"}
	devise_for :admin_users, ActiveAdmin::Devise.config

	get 'home' => 'static_pages#home'
	get 'about' => 'static_pages#about'
	get 'tos' => 'static_pages#tos'
	get 'privacy' => 'static_pages#privacy'

	resources :products, only: [:show]
	resources :users
	resources :requests, only: [:new, :create, :show]
	resources :sitemap, only: [:index]

	resource :cart, only: [:show] do
		put 'add/', to: 'carts#add', as: :add_to
		put 'remove/', to: 'carts#remove', as: :remove_from
		get 'checkout/', to: 'carts#checkout'
	end

	post '/hook' => 'carts#hook'

	get 'orders/' => 'orders#index'
	get 'orders/form' => 'orders#form'
	get 'orders/:id/payment' => 'orders#payment', as: :payment

end

app/views/shared/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Youniverse</h5>
        <p class="grey-text text-lighten-4">Diseños impresos para vestir original :)</p>


      </div>
      <div class="col l3 s12">
        <ul>
          <li><%= link_to 'Políticas de privacidad', privacy_path, class: 'white-text' %></li>
          <li><%= link_to 'Términos del servicio', tos_path, class: 'white-text' %></li>
          <li><%= link_to 'Sobre nosotros', about_path, class: 'white-text' %></li>
          <li><a class="white-text" href="#!">Políticas de reembolso</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      © 2016 Youniverse
    </div>
  </div>
</footer>

app/views/shared/_ga_script.html.erb
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-68835531-1', 'auto');
    ga('send', 'pageview');
</script>

app/views/shared/_header.html.erb
<!-- Menu bar -->
<nav class="light-blue darken-1" role="navigation">
  <div class="nav-wrapper container">
    <%= link_to root_path, class: 'brand-logo' do %>
        <%= image_tag('ynvs-logo.png', alt: 'youniverse', with: 60, height: 60) %>
    <% end %>

    <% if user_signed_in? %>
        <div class="hide-on-med-and-down" style="float: right; margin-left: 30px;">
          <%= link_to 'Enviar diseño', new_request_path, class: 'waves-effect waves-light btn' %>
        </div>
    <% end %>

    <!-- Standard menu -->
    <ul class="right hide-on-med-and-down">
      <% if user_signed_in? %>
          <li><%= link_to current_user.name, current_user %></li>
          <li>
            <%= link_to cart_path do %>
                Mi carrito (<span class="cart-count"><%= current_user.cart_count %></span>)
            <% end %>
          </li>
          <li><%= link_to 'Salir', destroy_user_session_path %></li>
      <% else %>
          <li><a href="#login-form-modal" class="modal-trigger">Iniciar sesión</a></li>
      <% end %>
    </ul>
    <!-- End Standard menu -->

    <!-- Mobile menu -->
    <ul id="nav-mobile" class="side-nav" style="left: -250px;">
      <% if user_signed_in? %>
          <li><%= link_to current_user.name, current_user %></li>
          <li><%= link_to "Logout", destroy_user_session_path %></li>
          <li><%= link_to 'Enviar diseño', new_request_path, class: 'waves-effect waves-light btn' %></li>
      <% else %>
          <li><a href="#login-form-modal" class="modal-trigger">Sign in</a></li>
      <% end %>
    </ul>
    <!-- End Mobile menu -->

    <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
  </div>
</nav>
<!-- End Menu bar -->

app/views/shared/_login_modal.html.erb
<!-- Login form modal -->
<div id="login-form-modal" class="modal" style="width: 100%">
  <div class="modal-content">
    <div class="row">
      <div class="col s12">

        <div class="valign center">
          <h4>Iniciar sesión</h4><br/>
        </div>

        <div class="row center">
          <div class="col s12">
            <% ['facebook'].each do |provider| %>
                <%= link_to omniauth_authorize_path('user', provider), class: "login-facebook btn waves-effect waves-light light-blue darken-4" do %>
                    <i class="mdi mdi-google left"></i> <%= "Iniciar con #{provider.to_s.titleize}" %>
                <% end %>
                <br/>
            <% end %>
          </div>
        </div>

        <div class="row center">
          <p class="small">No publicamos nada en tus cuentas sin tu permiso.
            Para más información, mira la sección de <a href="#">FAQ's</a>.</p>
        </div>

      </div>
    </div>
  </div>
</div>
<!-- End Login form modal -->

app/views/shared/_mp_script.html.erb
<!-- start Mixpanel -->
<script type="text/javascript">(function (e, b) {
    if (!b.__SV) {
        var a, f, i, g;
        window.mixpanel = b;
        b._i = [];
        b.init = function (a, e, d) {
            function f(b, h) {
                var a = h.split(".");
                2 == a.length && (b = b[a[0]], h = a[1]);
                b[h] = function () {
                    b.push([h].concat(Array.prototype.slice.call(arguments, 0)))
                }
            }

            var c = b;
            "undefined" !== typeof d ? c = b[d] = [] : d = "mixpanel";
            c.people = c.people || [];
            c.toString = function (b) {
                var a = "mixpanel";
                "mixpanel" !== d && (a += "." + d);
                b || (a += " (stub)");
                return a
            };
            c.people.toString = function () {
                return c.toString(1) + ".people (stub)"
            };
            i = "disable time_event track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.union people.track_charge people.clear_charges people.delete_user".split(" ");
            for (g = 0; g < i.length; g++)f(c, i[g]);
            b._i.push([a, e, d])
        };
        b.__SV = 1.2;
        a = e.createElement("script");
        a.type = "text/javascript";
        a.async = !0;
        a.src = "undefined" !== typeof MIXPANEL_CUSTOM_LIB_URL ? MIXPANEL_CUSTOM_LIB_URL : "file:" === e.location.protocol && "//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//) ? "https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js" : "//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";
        f = e.getElementsByTagName("script")[0];
        f.parentNode.insertBefore(a, f)
    }
})(document, window.mixpanel || []);
mixpanel.init("90f9ebd7b0809827c4daaf2f52f1b846");</script><!-- end Mixpanel -->