config/routes.rb
Rails.application.routes.draw do

	root 'static_pages#home'

	ActiveAdmin.routes(self)

	devise_for :users, controllers: {omniauth_callbacks: "omniauth_sessions"}
	devise_for :admin_users, ActiveAdmin::Devise.config

	get 'home' => 'static_pages#home'
	get 'about' => 'static_pages#about'
	get 'tos' => 'static_pages#tos'
	get 'privacy' => 'static_pages#privacy'

	resources :products, only: [:show]
	resources :users
	resources :requests, only: [:new, :create, :show]
	resources :sitemap, only: [:index]

	resource :cart, only: [:show] do
		put 'add/', to: 'carts#add', as: :add_to
		put 'remove/', to: 'carts#remove', as: :remove_from
		get 'checkout/', to: 'carts#checkout'
	end

	post '/hook' => 'carts#hook'

	get 'orders/' => 'orders#index'
	get 'orders/form' => 'orders#form'
	get 'orders/:id/payment' => 'orders#payment', as: :payment

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	before_action :authenticate_user!, except: [:hook]

	def show
		@cart_items = current_user.get_current_order.order_items
	end

	def add
		current_order = current_user.get_current_order

		new_item = OrderItem.new
		new_item.model_item = ModelItem.find(params[:item_id])
		new_item.size = params[:size]
		new_item.total_price = new_item.model_item.price * 1  # item price * quantity
		new_item.order = current_order

		if new_item.save
			render json: current_user.cart_count, status: :created
		else
			render json: new_item.errors, status: :unprocessable_entity
		end
	end

	def remove
		# $redis.srem current_user_cart, params[:product_id]
		# render json: current_user.cart_count, status: 200
	end

	def checkout
		order_to_process = current_user.get_current_order
		redirect_to order_to_process.paypal_url(payment_path(order_to_process))
	end


	protect_from_forgery except: [:hook]
	def hook
		params.permit! # Permit all Paypal input params

		status = params[:payment_status]
		if status == 'Completed'
			transaction_order = Order.find(params[:invoice])
			Payment.create channel: 'paypal', notification_params: params, status: status,
			               transaction_id: params[:txn_id], purchased_at: Time.now, order: transaction_order

			transaction_order.is_archived = true
			transaction_order.save

		end
		render nothing: true
	end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<div id="mycart">
  <div class="p1 glassy-bg mb1 text-center radius-l1 radius-r1">
    <h4>Carrito de compras</h4>

    <p class="mb0"> Has seleccionado <span class="cart-count"><%= current_user.cart_count %></span> productos!</p>
  </div>

  <div class="row">

    <% @cart_items.each do |item| %>
        <div class="col l4">
          <div data-equalizer class="cart-movie large-12 column mb1">
            <%= link_to '' do %>
                <%= image_tag item.model_item.image.url(:thumb), class: "radius-l1" %>
            <% end %>
            <div class="column large-7 glassy-bg text-center" data-equalizer-watch>
              <p class="scale ptm"> <%= item.model_item.model.name %> </p>
            </div>
          </div>
        </div>
    <% end %>
  </div>

  <% if @cart_items.exists? %>

      <div class="row">
        <%= link_to checkout_cart_path do %>
            <%= image_tag 'https://www.paypal.com/en_US/i/btn/btn_xpressCheckout.gif', align: 'left', style:'margin-right:7px;' %>
        <% end %>
      </div>

  <% end %>
</div>