config/routes.rb
Rails.application.routes.draw do

	root 'static_pages#home'

	ActiveAdmin.routes(self)

	devise_for :users, controllers: {omniauth_callbacks: "omniauth_sessions"}
	devise_for :admin_users, ActiveAdmin::Devise.config

	get 'home' => 'static_pages#home'
	get 'about' => 'static_pages#about'
	get 'tos' => 'static_pages#tos'
	get 'privacy' => 'static_pages#privacy'

	resources :products, only: [:show]
	resources :users
	resources :requests, only: [:new, :create, :show]
	resources :sitemap, only: [:index]

	resource :cart, only: [:show] do
		put 'add/', to: 'carts#add', as: :add_to
		put 'remove/', to: 'carts#remove', as: :remove_from
		get 'checkout/', to: 'carts#checkout'
	end

	post '/hook' => 'carts#hook'

	get 'orders/' => 'orders#index'
	get 'orders/form' => 'orders#form'
	get 'orders/:id/payment' => 'orders#payment', as: :payment

end

app/models/product.rb
class Product < ActiveRecord::Base

	has_many :models, :dependent => :destroy

	has_attached_file :design_image,
	                  :path => ':rails_root/public/system/:class/:attachment/:id/:basename_:style.:extension',
	                  :url => '/system/:class/:attachment/:id/:basename_:style.:extension',
	                  :default_url => 'default/design/:style/missing.png',
	                  :styles => {
			                  :thumb => ['100x100#', :jpg, :quality => 70],
			                  :preview => ['480x480#', :jpg, :quality => 70],
			                  :large => ['600>', :jpg, :quality => 70],
			                  :retina => ['1200>', :jpg, :quality => 30]
	                  },
	                  :convert_options => {
			                  :thumb => '-set colorspace sRGB -strip',
			                  :preview => '-set colorspace sRGB -strip',
			                  :large => '-set colorspace sRGB -strip',
			                  :retina => '-set colorspace sRGB -strip -sharpen 0x0.5'
	                  }

	validates_attachment :design_image,
	                     :presence => true,
	                     :size => {:in => 0..10.megabytes},
	                     :content_type => {:content_type => /^image\/(jpeg|png|gif)$/}

	validates :name, presence: true, uniqueness: true
	validates :description, presence: true, length: {
			minimum: 2,
			maximum: 200,
			too_short: "must have at least %{count} words",
			too_long: "must have at most %{count} words"
	}

	def to_s
		"#{name}"
	end


	def cart_action(current_user_id)
		if $redis.sismember "cart#{current_user_id}", id
			"Remove from"
		else
			"Add to"
		end
	end

	def featured_model_item
		first_model = self.models.first
		# byebug
		first_model.model_items.first  # get first model item created
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	# GET /products/1
	def show
		@product = Product.find(params[:id])
		@cart_action = @product.cart_action current_user.try :id
	end

	private
	def product_params
		params.require(:product).permit(:name, :description, :design_image, :published)
	end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/show.html.erb
<div class="container">
  <div class="row">
    <div class="col l8">
      <div class="row">
        <div class="col l12">
          <div id="image">
            <%= image_tag @product.design_image.url(:large), width: '500' %>

          </div>
        </div>
      </div>
      <div class="row model-options">
        <div class="col l12">
          <% @product.models.each do |model| %>
              <% model.model_items.each do |item| %>
                  <%= link_to '', class: 'image', rel: item.image.url(:large), sex: item.sex, price: item.price, id: item.id do %>
                      <%= image_tag item.image.url(:thumb), class: 'thumb' %>
                  <% end %>
              <% end %>
          <% end %>

          <%= link_to '', class: 'image', rel: @product.design_image.url(:large) do %>
              <%= image_tag @product.design_image.url(:thumb), class: 'thumb selected' %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col s4">

      <input type="hidden" name="item-id"/>
      <input type="hidden" name="item-sex"/>
      <input type="hidden" name="item-price"/>

      <h4><%= @product.name %></h4>
      <p style="text-align: center; font-size: smaller; margin: 0;"><strong>5</strong> vendidos</p>
      <p style="text-align: center; font-size: smaller; margin: 0;"><strong>7</strong> más para imprimir</p>
      <p style="text-align: center; font-size: smaller; margin: 0;"><strong>8</strong> días restantes</p>

      <p><%= @product.description %></p>

      <br/><br/>

      <div class="size-options">
        <p><strong>* Select a model below</strong></p>
      </div>

      <div class="item-price"></div>

      <!--<div ng-controller="PageViewCtrl as pageView">-->
        <!--{{ pageView.name }}-->
      <!--</div>-->

      <br/><br/><br/>

      <% if signed_in? %>
          <%= link_to '', id: 'add-to-cart-button', class: 'waves-effect waves-light btn light-blue darken-1', data: {url: add_to_cart_path} do %>
              <i class="material-icons left">shopping_cart</i>Agregar al carrito
          <% end %>
      <% else %>
          <%= link_to '', class: 'waves-effect waves-light btn light-blue darken-1', onClick: "alert('Antes debes iniciar sesión!')" do %>
              <i class="material-icons left">shopping_cart</i>Agregar al carrito
          <% end %>
      <% end %>
    </div>
  </div>
</div>